In [2]:
import numpy as np

In [26]:
batts=[]
linecount = 0
with open('input_03.txt') as f:
    for line in f:
        batts.append(list(map(int,line.strip())))
battarr=np.array(batts)
numbanks=battarr.shape[0]
numbatts=battarr.shape[1]
print(numbanks,numbatts,battarr)

200 100 [[5 3 7 ... 7 4 5]
 [5 2 2 ... 4 6 4]
 [3 6 3 ... 4 2 4]
 ...
 [2 2 1 ... 1 2 2]
 [8 7 9 ... 3 6 7]
 [2 2 2 ... 1 2 2]]


In [27]:
jolts=0
for bank in range(numbanks):
    tens=np.max(battarr[bank,:-1])
    postens=np.argmax((battarr[bank,:-1]))
    ones=np.max(battarr[bank,postens+1:])
    jolt=tens*10+ones
    print(postens,tens,ones,tens*10+ones)
    jolts += jolt
print (jolts)

73 9 7 97
23 8 7 87
33 9 8 98
52 8 7 87
21 9 8 98
98 8 9 89
7 9 9 99
10 9 9 99
78 7 5 75
37 7 7 77
64 9 7 97
16 9 9 99
26 9 9 99
8 9 9 99
41 9 9 99
17 8 8 88
23 9 9 99
0 8 8 88
38 9 7 97
43 7 7 77
57 9 9 99
30 8 6 86
52 9 9 99
11 8 8 88
20 7 7 77
30 7 7 77
69 7 7 77
0 9 6 96
8 7 5 75
12 9 9 99
30 9 9 99
40 9 9 99
15 5 5 55
4 6 5 65
4 7 6 76
86 9 5 95
13 9 9 99
31 9 9 99
87 7 6 76
20 9 9 99
55 6 5 65
79 9 8 98
69 8 5 85
82 9 5 95
65 5 4 54
72 8 8 88
12 8 8 88
26 9 9 99
54 6 6 66
40 8 8 88
19 6 5 65
10 9 9 99
86 9 8 98
93 7 4 74
47 8 7 87
13 7 6 76
39 6 6 66
11 9 6 96
77 9 9 99
82 9 8 98
96 9 5 95
25 6 6 66
43 7 7 77
10 5 5 55
16 8 8 88
87 9 7 97
31 5 5 55
98 4 2 42
49 9 9 99
29 9 9 99
31 6 5 65
13 9 8 98
66 9 6 96
0 9 9 99
28 9 9 99
3 9 8 98
23 9 6 96
0 9 9 99
82 9 7 97
69 5 3 53
63 8 5 85
15 9 9 99
6 7 7 77
15 9 9 99
21 8 7 87
21 7 6 76
11 7 6 76
88 7 5 75
38 5 4 54
24 9 9 99
16 9 9 99
5 9 9 99
58 9 9 99
7 6 5 65
32 5 5 55
38 9 7 97
8 8 6 86
6 9 6 96
21 8 8 88
38 8 8 88
57 9 6 96
65 9 

In [28]:
#b 12 digits
jolts=0
digits=12
for bank in range(numbanks):
    start=0
    jolt=0
    print(battarr[bank,:])
    for digit in range(digits):
        #print(digit,start,digits-digit,battarr[bank,start:numbatts-(digits-digit-1)])
        digval=np.max(battarr[bank,start:numbatts-(digits-digit-1)])
        #print(digit,start,digits-digit,battarr[bank,start:numbatts-(digits-digit-1)],digval)
        start=np.argmax(battarr[bank,start:numbatts-(digits-digit-1)])+1+start
        jolt = jolt*10 + digval
    print(battarr[bank,:],jolt)
    jolts += jolt
print (jolts)

[5 3 7 3 4 7 5 2 6 3 7 5 3 2 5 8 3 3 6 4 2 3 4 4 2 2 5 4 7 4 6 2 6 3 3 3 2
 3 3 4 2 3 2 2 1 7 3 3 4 4 3 1 3 3 7 4 6 4 3 4 2 7 2 6 8 7 3 1 2 5 2 2 3 9
 3 2 3 1 2 3 6 3 6 7 5 1 7 5 4 3 5 3 2 4 3 4 3 7 4 5]
[5 3 7 3 4 7 5 2 6 3 7 5 3 2 5 8 3 3 6 4 2 3 4 4 2 2 5 4 7 4 6 2 6 3 3 3 2
 3 3 4 2 3 2 2 1 7 3 3 4 4 3 1 3 3 7 4 6 4 3 4 2 7 2 6 8 7 3 1 2 5 2 2 3 9
 3 2 3 1 2 3 6 3 6 7 5 1 7 5 4 3 5 3 2 4 3 4 3 7 4 5] 977554343745
[5 2 2 7 3 2 1 2 3 2 6 1 7 2 4 2 4 2 4 1 2 1 7 8 3 2 2 2 4 4 4 2 2 2 4 7 5
 3 6 3 2 1 2 2 1 3 3 2 1 2 2 2 1 3 2 3 4 2 2 2 2 2 1 4 2 3 4 3 2 3 2 4 3 2
 2 1 3 2 4 3 1 3 5 4 4 2 3 5 4 2 6 3 1 2 2 2 2 4 6 4]
[5 2 2 7 3 2 1 2 3 2 6 1 7 2 4 2 4 2 4 1 2 1 7 8 3 2 2 2 4 4 4 2 2 2 4 7 5
 3 6 3 2 1 2 2 1 3 3 2 1 2 2 2 1 3 2 3 4 2 2 2 2 2 1 4 2 3 4 3 2 3 2 4 3 2
 2 1 3 2 4 3 1 3 5 4 4 2 3 5 4 2 6 3 1 2 2 2 2 4 6 4] 876632222464
[3 6 3 4 4 3 6 8 2 5 6 8 5 7 6 4 7 4 2 6 7 3 8 5 3 3 5 5 6 3 2 4 4 9 7 3 8
 6 4 8 3 8 5 2 3 4 3 3 7 7 3 8 1 8 4 4 3 6 5 5 3 4 6 8 4 2 2 2 2 7 8 2 8 6
 3 3 7 2