In [1]:
import numpy as np

In [9]:
# Define addition operation function
def add(a, b):
    return a+b

# Define subtraction operation function
def sub(a, b):
    return a-b

# Define multiplication operation function
def mul(a, b):
    return a*b

# Define division operation function
def div(a, b):
    return a/b

In [63]:
data=[]
with open('test_06.txt') as f:
    for line in f:
        data.append(line.strip().split())
print(data,len(data))
dataarr = np.array(data[:-1],dtype=int)
oparr = np.array(data[-1])
numeqn = dataarr.shape[1]
numops = dataarr.shape[0]
print(dataarr,oparr,numeqn,numops)

[['123', '328', '51', '64'], ['45', '64', '387', '23'], ['6', '98', '215', '314'], ['*', '+', '*', '+']] 4
[[123 328  51  64]
 [ 45  64 387  23]
 [  6  98 215 314]] ['*' '+' '*' '+'] 4 3


In [64]:
chksum=0
for eqn in range(numeqn):
    value = dataarr[0,eqn]
    for item in range(1,numops):
        if oparr[eqn]=="+":
            value += dataarr[item,eqn]
        else: # mult
            value *= dataarr[item,eqn]
    print(value)
    chksum+=value
print(chksum)

33210
490
4243455
401
4277556


In [59]:
#b - reread data


In [65]:
data=[]
with open('test_06.txt') as f:
    for line in f:
        data.append(list(line.strip('\n')))
print(data,len(data))
for line in data:
    print (line,len(line))
dataarr = np.array(data[:-1])
#oparr = np.array(data[-1])
numcols = dataarr.shape[1]
numops = dataarr.shape[0]
print(dataarr,oparr,numeqn,numops)

[['1', '2', '3', ' ', '3', '2', '8', ' ', ' ', '5', '1', ' ', '6', '4', ' '], [' ', '4', '5', ' ', '6', '4', ' ', ' ', '3', '8', '7', ' ', '2', '3', ' '], [' ', ' ', '6', ' ', '9', '8', ' ', ' ', '2', '1', '5', ' ', '3', '1', '4'], ['*', ' ', ' ', ' ', '+', ' ', ' ', ' ', '*', ' ', ' ', ' ', '+', ' ', ' ']] 4
['1', '2', '3', ' ', '3', '2', '8', ' ', ' ', '5', '1', ' ', '6', '4', ' '] 15
[' ', '4', '5', ' ', '6', '4', ' ', ' ', '3', '8', '7', ' ', '2', '3', ' '] 15
[' ', ' ', '6', ' ', '9', '8', ' ', ' ', '2', '1', '5', ' ', '3', '1', '4'] 15
['*', ' ', ' ', ' ', '+', ' ', ' ', ' ', '*', ' ', ' ', ' ', '+', ' ', ' '] 15
[['1' '2' '3' ' ' '3' '2' '8' ' ' ' ' '5' '1' ' ' '6' '4' ' ']
 [' ' '4' '5' ' ' '6' '4' ' ' ' ' '3' '8' '7' ' ' '2' '3' ' ']
 [' ' ' ' '6' ' ' '9' '8' ' ' ' ' '2' '1' '5' ' ' '3' '1' '4']] ['*' '+' '*' '+'] 4 3


In [66]:
opcount = 0
chksum = 0
operation = oparr[numeqn - opcount -1]
if operation == "+":
    value = 0
else: #mult
    value = 1
for number in range(numcols-1,-1,-1):
    operand=dataarr[0,number]
    for digit in dataarr[1:,number]:
        operand += digit
    if operand.isspace():
        print(value)
        chksum+=value
        opcount += 1
        operation = oparr[numeqn - opcount -1]
        if operation == "+":
            value = 0
        else: #mult
            value = 1
    else:
        operand = int(operand)
        print (operation,operand)
        if operation == "+":
            value += operand
        else:
            value *= operand 
print(value)
chksum+=value
opcount += 1
print(chksum)

+ 4
+ 431
+ 623
1058
* 175
* 581
* 32
3253600
+ 8
+ 248
+ 369
625
* 356
* 24
* 1
8544
3263827
