In [2]:
import numpy as np



In [27]:
area=[]
linecount = 0
with open('test_07.txt') as f:
    for line in f:
        area.append(list(line.strip()))
maparr=np.array(area)
length=maparr.shape[0]
width=maparr.shape[1]
print(width, length,maparr)


15 16 [['.' '.' '.' '.' '.' '.' '.' 'S' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '^' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '^' '.' '^' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '^' '.' '^' '.' '^' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '^' '.' '^' '.' '.' '.' '^' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '^' '.' '^' '.' '.' '.' '^' '.' '^' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '^' '.' '.' '.' '^' '.' '.' '.' '.' '.' '^' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.']
 ['.' '^' '.' '^' '.' '^' '.' '^' '.' '^' '.' '.' '.' '^' '.']
 ['.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.' '.'

In [28]:
#a
#Find start
start = np.array(np.where(maparr=="S"))[:,0]
print(start)
maparr[start[0]+1,start[1]]="|"
splits = 0
for row in range(1,length-1):
    beams = np.array(np.where(maparr[row,:]=="|"))[0]
    for beam in beams:
        if maparr[row+1,beam]=="^":
            splits+=1
            maparr[row+1,beam+1]="|"
            maparr[row+1,beam-1]="|"
        else: # vacuum
            maparr[row+1,beam]="|"
print(maparr,splits)


[0 7]
[['.' '.' '.' '.' '.' '.' '.' 'S' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '.' '|' '.' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '|' '^' '|' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '.' '|' '.' '|' '.' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '|' '^' '|' '^' '|' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '.' '|' '.' '|' '.' '|' '.' '.' '.' '.' '.']
 ['.' '.' '.' '.' '|' '^' '|' '^' '|' '^' '|' '.' '.' '.' '.']
 ['.' '.' '.' '.' '|' '.' '|' '.' '|' '.' '|' '.' '.' '.' '.']
 ['.' '.' '.' '|' '^' '|' '^' '|' '|' '|' '^' '|' '.' '.' '.']
 ['.' '.' '.' '|' '.' '|' '.' '|' '|' '|' '.' '|' '.' '.' '.']
 ['.' '.' '|' '^' '|' '^' '|' '|' '|' '^' '|' '^' '|' '.' '.']
 ['.' '.' '|' '.' '|' '.' '|' '|' '|' '.' '|' '.' '|' '.' '.']
 ['.' '|' '^' '|' '|' '|' '^' '|' '|' '.' '|' '|' '^' '|' '.']
 ['.' '|' '.' '|' '|' '|' '.' '|' '|' '.' '|' '|' '.' '|' '.']
 ['|' '^' '|' '^' '|' '^' '|' '^' '|' '^' '|' '|' '|' '^' '|']
 ['|' '.' '|' '.' '|' '.' '|' '.' '|' '.' '|' '|'

In [29]:
#b
#Find start
start = np.array(np.where(maparr=="S"))[:,0]
worlds = np.zeros_like(maparr, dtype=int)
print(worlds)
worlds[start[0]+1,start[1]]=1
for row in range(1,length-1):
    beams = np.array(np.where(worlds[row,:]>0))[0]
    for beam in beams:
        numworld = worlds[row,beam]
        if maparr[row+1,beam]=="^":
            worlds[row+1,beam+1]+= numworld
            worlds[row+1,beam-1]+= numworld
        else: # vacuum
            worlds[row+1,beam]+= numworld
print(worlds,np.sum(worlds[-1,:]))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  2  0  1  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  2  0  1  0  0  0  0  0]
 [ 0  0  0  0  1  0  3  0  3  0  1  0  0  0  0]
 [ 0  0  0  0  1  0  3  0  3  0  1  0  0  0  0]
 [ 0  0  0  1  0  4  0  3  3  1  0  1  0  0  0]
 [ 0  0  0  1  0  4  0  3  3  1  0  1  