In [1]:
import numpy as np
import pandas as pd

In [56]:
safe=0
with open('input_02.txt') as f:
    for line in f:
        condition=np.array(list(map(int,line.strip().split())))
        print(condition)
        status=1
        if (condition.size>1):
            if condition[1]>condition[0]:
                incr=1
            elif condition[1]<condition[0]:
                incr=-1
            else:
                print(condition," is unsafe")
                incr=0
                status=0
            #    continue
            for i in range(1,np.size(condition)):
                if incr*(condition[i]-condition[i-1])<=0 or incr*(condition[i]-condition[i-1])>3:
                    print(condition,"is unsafe")
                    status=0
                    break
            if status==1:
                print(condition," is safe")
                safe += 1
            else: #Unsafe
                for skip in range(np.size(condition)):
                    status=1
                    short=np.delete(condition,skip)
                    if (short.size>1):
                        if short[1]>short[0]:
                            incr=1
                        elif short[1]<short[0]:
                            incr=-1
                        else:
                            print(short," is unsafe")
                            incr=0
                            status=0
                            #continue
                        for i in range(1,np.size(short)):
                            if incr*(short[i]-short[i-1])<=0 or incr*(short[i]-short[i-1])>3:
                                print(short,"is unsafe at ",i)
                                status=0
                                break
                        if status==1:
                            print(short," is safe")
                            safe +=1
                            break

        else:
            raise(ValueError)
print(safe)

[40 42 45 46 49 47]
[40 42 45 46 49 47] is unsafe
[42 45 46 49 47] is unsafe at  4
[40 45 46 49 47] is unsafe at  1
[40 42 46 49 47] is unsafe at  2
[40 42 45 49 47] is unsafe at  3
[40 42 45 46 47]  is safe
[65 66 68 71 72 72]
[65 66 68 71 72 72] is unsafe
[66 68 71 72 72] is unsafe at  4
[65 68 71 72 72] is unsafe at  4
[65 66 71 72 72] is unsafe at  2
[65 66 68 72 72] is unsafe at  3
[65 66 68 71 72]  is safe
[44 46 49 52 55 59]
[44 46 49 52 55 59] is unsafe
[46 49 52 55 59] is unsafe at  4
[44 49 52 55 59] is unsafe at  1
[44 46 52 55 59] is unsafe at  2
[44 46 49 55 59] is unsafe at  3
[44 46 49 52 59] is unsafe at  4
[44 46 49 52 55]  is safe
[62 63 66 68 71 74 80]
[62 63 66 68 71 74 80] is unsafe
[63 66 68 71 74 80] is unsafe at  5
[62 66 68 71 74 80] is unsafe at  1
[62 63 68 71 74 80] is unsafe at  2
[62 63 66 71 74 80] is unsafe at  3
[62 63 66 68 74 80] is unsafe at  4
[62 63 66 68 71 80] is unsafe at  5
[62 63 66 68 71 74]  is safe
[20 23 25 24 26]
[20 23 25 24 26] is unsaf

In [28]:
print(condition.size)

5
