In [36]:
import numpy as np
import re
directions=np.array([[1,0],[0,1],[-1,0],[0,-1]])

In [41]:
dimx=71
dimy=71
numbytes=1024
bytelist=[]
linecount = 0
with open('input_18.txt') as f:
    for line in f:
        m=re.match('([0-9]+),([0-9]+)',line)
        bytelist.append([int(m.group(1)),int(m.group(2))])
bytelist=np.array(bytelist)
maparr=np.full((dimx,dimy),'.',dtype=str)
print(maparr)
for count,block in enumerate(bytelist):
    print(count,block)
    maparr[block[0],block[1]]='#'
    if count==numbytes-1:
        break
maparr[0,0]='S'
maparr[-1,-1]='E'
print(maparr.transpose(),dimx,dimy)

[['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ...
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']]
0 [61 50]
1 [57 56]
2 [44 69]
3 [39 59]
4 [62 41]
5 [62 63]
6 [39 56]
7 [53 44]
8 [21  4]
9 [49  4]
10 [51 13]
11 [33 52]
12 [69 29]
13 [69 48]
14 [51 53]
15 [47  7]
16 [ 1 27]
17 [51  6]
18 [ 6 33]
19 [49 43]
20 [69 47]
21 [47 61]
22 [53  4]
23 [4 1]
24 [45 61]
25 [45  8]
26 [ 7 27]
27 [25  9]
28 [18  7]
29 [21  7]
30 [66 51]
31 [52 69]
32 [65 49]
33 [35  5]
34 [ 5 40]
35 [29  7]
36 [19  9]
37 [48  1]
38 [13 33]
39 [ 8 11]
40 [69 57]
41 [ 3 10]
42 [48 53]
43 [27  1]
44 [54 59]
45 [53 53]
46 [ 5 21]
47 [69 58]
48 [66 65]
49 [61 58]
50 [40 47]
51 [51 46]
52 [11  1]
53 [38 69]
54 [68 43]
55 [45 69]
56 [19  3]
57 [5 4]
58 [ 3 18]
59 [ 5 23]
60 [35  2]
61 [45 67]
62 [59 64]
63 [37  9]
64 [ 6 13]
65 [ 6 17]
66 [49 41]
67 [67 43]
68 [51 47]
69 [51 11]
70 [67 53]
71 [53 67]
72 [11 36]
73 [7 9]
74 [45 49]

In [42]:
#Find Start
[startx,starty]=np.where(maparr=="S")
start=np.array([startx[0],starty[0]])
print(start)
startdir=1
#Find target
[targetx,targety]=np.where(maparr=="E")
target=np.array([targetx[0],targety[0]])
print(target)

[0 0]
[70 70]


In [43]:
visited=np.full((dimx,dimy),-1)
locs=np.array([start])
visited[start[0],start[1]]=0
while len(locs)>0:
    #print('New round')
    newlocs=[]
    #newdirs=[]
    #newcosts=[]
    for loc in locs:
        cost=visited[loc[0],loc[1]]
        #print('Location', loc,'Cost',cost)
        for dir in directions:
            #print ('direction', dir)
            if loc[0]+dir[0]>=0 and loc[1]+dir[1]>=0 and loc[0]+dir[0]<dimx and loc[1]+dir[1]<dimy:
                if maparr[loc[0]+dir[0],loc[1]+dir[1]]!='#' and visited[loc[0]+dir[0],loc[1]+dir[1]]==-1:
                    #print('Success')
                    newlocs.append(loc+dir)
                    visited[loc[0]+dir[0],loc[1]+dir[1]]=cost+1
        locs=np.array(np.unique(newlocs,axis=0))
        #locs=np.array(newlocs)
print(visited.transpose())
print('Final',visited[target[0],target[1]])



[[  0   1   2 ... 128 129 130]
 [  1  -1  -1 ... 127 128 129]
 [  2  -1  88 ... 126 127 128]
 ...
 [170 169 168 ... 266  -1 272]
 [171 170 169 ... 267  -1 271]
 [172 171 170 ... 268 269 270]]
Final 270


In [44]:
for count in range(numbytes,bytelist.shape[0]):
    maparr[bytelist[count,0],bytelist[count,1]]='#'
    print(count,bytelist[count,:])
    visited=np.full((dimx,dimy),-1)
    locs=np.array([start])
    visited[start[0],start[1]]=0
    while len(locs)>0:
        #print('New round')
        newlocs=[]
    #newdirs=[]
    #newcosts=[]
        for loc in locs:
            cost=visited[loc[0],loc[1]]
            #print('Location', loc,'Cost',cost)
            for dir in directions:
                #print ('direction', dir)
                if loc[0]+dir[0]>=0 and loc[1]+dir[1]>=0 and loc[0]+dir[0]<dimx and loc[1]+dir[1]<dimy:
                    if maparr[loc[0]+dir[0],loc[1]+dir[1]]!='#' and visited[loc[0]+dir[0],loc[1]+dir[1]]==-1:
                        #print('Success')
                        newlocs.append(loc+dir)
                        visited[loc[0]+dir[0],loc[1]+dir[1]]=cost+1
            locs=np.array(np.unique(newlocs,axis=0))
            #locs=np.array(newlocs)
    #print(visited.transpose())
    print('Final',visited[target[0],target[1]])
    if visited[target[0],target[1]]==-1:
        print('Broken! by block',count,bytelist[count,:])
        break




1024 [ 8 43]
Final 270
1025 [33 66]
Final 270
1026 [35 39]
Final 270
1027 [ 2 59]
Final 270
1028 [67 15]
Final 270
1029 [49 21]
Final 270
1030 [16 35]
Final 270
1031 [ 7 47]
Final 270
1032 [23 62]
Final 270
1033 [33 14]
Final 270
1034 [11 45]
Final 270
1035 [53 22]
Final 270
1036 [43 41]
Final 270
1037 [ 1 56]
Final 270
1038 [47 31]
Final 270
1039 [15 55]
Final 270
1040 [27 43]
Final 270
1041 [ 1 59]
Final 270
1042 [25 21]
Final 270
1043 [26 33]
Final 270
1044 [39 21]
Final 270
1045 [65 28]
Final 270
1046 [ 3 65]
Final 270
1047 [47 19]
Final 270
1048 [15 25]
Final 270
1049 [61  2]
Final 270
1050 [49 23]
Final 270
1051 [ 8 53]
Final 270
1052 [61 61]
Final 270
1053 [30 19]
Final 270
1054 [ 2 53]
Final 270
1055 [19 68]
Final 270
1056 [53 15]
Final 270
1057 [28 45]
Final 270
1058 [43 46]
Final 270
1059 [44 31]
Final 270
1060 [37 14]
Final 270
1061 [40 45]
Final 270
1062 [23 29]
Final 270
1063 [11 60]
Final 270
1064 [63 11]
Final 270
1065 [ 8 67]
Final 270
1066 [36 65]
Final 270
1067 [30 29