In [2]:
import numpy as np
directions=np.array([[1,0],[0,1],[-1,0],[0,-1]])

In [3]:
area=[]
linecount = 0
with open('input_20.txt') as f:
    for line in f:
        area.append(list(line.strip()))
maparr=np.array(area)
dimx=maparr.shape[0]
dimy=maparr.shape[1]
print(dimx,dimy,maparr)
maparrorig=maparr.copy()
#Find Start
[startx,starty]=np.where(maparr=="S")
start=np.array([startx[0],starty[0]])
print(start)
startdir=1
#Find target
[targetx,targety]=np.where(maparr=="E")
target=np.array([targetx[0],targety[0]])
print(target)

141 141 [['#' '#' '#' ... '#' '#' '#']
 ['#' '.' '.' ... '.' '.' '#']
 ['#' '.' '#' ... '#' '.' '#']
 ...
 ['#' '.' '#' ... '#' '.' '#']
 ['#' '.' '.' ... '.' '.' '#']
 ['#' '#' '#' ... '#' '#' '#']]
[ 69 101]
[65 77]


In [4]:
visited=np.full((dimx,dimy),-1)
wallvisited=np.full((dimx,dimy),-1)
locs=np.array([start])
visited[start[0],start[1]]=0
walls=[]
wallcosts=[]
shortcuts=[]
track=[start]
while len(locs)>0 and visited[target[0],target[1]]==-1:
    #print('New round')
    newlocs=[]
    #newdirs=[]
    #newcosts=[]
    for loc in locs:
        cost=visited[loc[0],loc[1]]
        #print('Location', loc,'Cost',cost)
        for dir in directions:
           # print ('direction', dir, 'target', loc+dir)
            #if loc[0]+dir[0]>=0 and loc[1]+dir[1]>=0 and loc[0]+dir[0]<dimx and loc[1]+dir[1]<dimy:
            if maparr[loc[0]+dir[0],loc[1]+dir[1]]!='#': 
                if visited[loc[0]+dir[0],loc[1]+dir[1]]==-1:
                    #print('Success')
                    newlocs.append(loc+dir)
                    track.append(loc+dir)
                    visited[loc[0]+dir[0],loc[1]+dir[1]]=cost+1
            elif all(loc+dir>=[0,0]) and all(loc+dir<[dimx,dimy]): #wall
                if wallvisited[loc[0]+dir[0],loc[1]+dir[1]]==-1:
                    wallvisited[loc[0]+dir[0],loc[1]+dir[1]]=cost+1
                elif wallvisited[loc[0]+dir[0],loc[1]+dir[1]]<cost-1: #shortcut
                    shortcuts.append(cost-wallvisited[loc[0]+dir[0],loc[1]+dir[1]]-1)
                    walls.append(loc+dir)
                    wallcosts.append(cost+1)
        locs=np.array(np.unique(newlocs,axis=0))
        #locs=np.array(newlocs)
#walls=np.array(np.unique(walls,axis=0))
track=np.array(track)
print(visited)
print(track)
print('Final',visited[target[0],target[1]])
basecost=visited[target[0],target[1]]
basevisited=visited.copy()
basewallvisited=wallvisited.copy()
shortcuts=np.array(shortcuts)
print(shortcuts)
print(np.unique(shortcuts,return_counts=True))

[[  -1   -1   -1 ...   -1   -1   -1]
 [  -1 5796 5797 ... 8325 8326   -1]
 [  -1 5795   -1 ...   -1 8327   -1]
 ...
 [  -1 3383   -1 ...   -1 1187   -1]
 [  -1 3382 3381 ... 1189 1188   -1]
 [  -1   -1   -1 ...   -1   -1   -1]]
[[ 69 101]
 [ 69 102]
 [ 69 103]
 ...
 [ 65  75]
 [ 65  76]
 [ 65  77]]
Final 9416
[   2    4    2 ... 2494 2496    2]
(array([   2,    4,    6,    8,   10,   12,   14,   16,   18,   20,   22,
         24,   26,   28,   30,   32,   34,   36,   38,   40,   42,   44,
         46,   48,   50,   52,   54,   56,   58,   60,   62,   64,   66,
         68,   70,   72,   74,   76,   78,   80,   82,   84,   86,   88,
         90,   92,   94,   96,   98,  100,  102,  104,  106,  108,  110,
        112,  114,  116,  118,  120,  122,  124,  126,  128,  130,  132,
        134,  136,  138,  140,  142,  144,  146,  148,  150,  152,  154,
        156,  158,  160,  162,  164,  166,  168,  170,  172,  174,  176,
        178,  180,  182,  184,  186,  188,  190,  192,  194,  196,  

In [8]:
len(shortcuts[(shortcuts>=100).nonzero()])

1369

costarr=np.zeros(walls.shape[0],dtype=int)
cheatcost=[]
for wall in walls:
    #maparr=maparrorig.copy()
    #maparr[wall[0],wall[1]]='C'
    visited=basevisited.copy()
    locs=np.array([wall])
    visited[wall[0],wall[1]]=wallvisited[wall[0],wall[1]]
    print(wall,visited[wall[0],wall[1]])

    cheatclock=1
    cheatdest=[]
    while len(locs)>0 and cheatclock<20:
        print('New round')
        cheatclock+=1
        newlocs=[]
    #newdirs=[]
    #newcosts=[]
        for loc in locs:
            cost=visited[loc[0],loc[1]]
            print('Location', loc,'Cost',cost)
            for dir in directions:
                print ('direction', dir, 'target', loc+dir)
            #if loc[0]+dir[0]>=0 and loc[1]+dir[1]>=0 and loc[0]+dir[0]<dimx and loc[1]+dir[1]<dimy:
                if all(loc+dir>=[0,0]) and all(loc+dir<[dimx,dimy]):
                    if maparr[loc[0]+dir[0],loc[1]+dir[1]]=='#': #move in walls
                        if visited[loc[0]+dir[0],loc[1]+dir[1]]==-1:
                            print('Success')
                            newlocs.append(loc+dir)
                            visited[loc[0]+dir[0],loc[1]+dir[1]]=cost+1
                    elif not (visited[loc[0]+dir[0],loc[1]+dir[1]] in cheatdest):
                        if (visited[loc[0]+dir[0],loc[1]+dir[1]]-cost-1)>0:
                            cheatdest.append(visited[loc[0]+dir[0],loc[1]+dir[1]])
                            cheatcost.append(visited[loc[0]+dir[0],loc[1]+dir[1]]-cost-1)
                            print('Found cheat',cheatcost[-1],cheatclock,wall,loc+dir,visited[loc[0]+dir[0],loc[1]+dir[1]],cost+1)
                    else: 
                        print('Found cheat again',wall,loc+dir,visited[loc[0]+dir[0],loc[1]+dir[1]])
                #elif all(loc+dir>=[0,0]) and all(loc+dir<[dimx,dimy]): #wall
                #    print('Wall', loc+dir)
                #    walls.append(loc+dir)
            locs=np.array(np.unique(newlocs,axis=0))
            #locs=np.array(newlocs)
    #print(visited.transpose())
    #print('Final',visited[target[0],target[1]])
    #costarr[count]=visited[target[0],target[1]]
    print(np.unique(cheatcost,return_counts=True))


In [6]:
print(track)

[[ 69 101]
 [ 69 102]
 [ 69 103]
 ...
 [ 65  75]
 [ 65  76]
 [ 65  77]]


In [9]:
shortcutsavings=[]
for step in track:
    print('Step', step)
    startcost=visited[step[0],step[1]]
    for i in range(step[0]-20,step[0]+20+1):
        if (i>=1 and i<dimx-1):
            for j in range(step[1]-(20-abs(i-step[0])),step[1]+(20-abs(i-step[0]))+1):
                if (j>=1 and j<dimy-1):
                    dist=abs(i-step[0])+abs(j-step[1])
                    #print(i,j,step,dist)
                    if visited[i,j]>0: #potential destination
                        if visited[i,j]>startcost+dist:
                            #found shortcut
                            shortcutsavings.append(visited[i,j]-startcost-dist)
                            #print('Shortcut', dist, step,[i,j],shortcutsavings[-1])
                       

Step [ 69 101]
Step [ 69 102]
Step [ 69 103]
Step [ 69 104]
Step [ 69 105]
Step [ 69 106]
Step [ 69 107]
Step [ 69 108]
Step [ 69 109]
Step [ 69 110]
Step [ 69 111]
Step [ 69 112]
Step [ 69 113]
Step [ 68 113]
Step [ 67 113]
Step [ 66 113]
Step [ 65 113]
Step [ 65 114]
Step [ 65 115]
Step [ 66 115]
Step [ 67 115]
Step [ 67 116]
Step [ 67 117]
Step [ 67 118]
Step [ 67 119]
Step [ 68 119]
Step [ 69 119]
Step [ 69 120]
Step [ 69 121]
Step [ 68 121]
Step [ 67 121]
Step [ 67 122]
Step [ 67 123]
Step [ 68 123]
Step [ 69 123]
Step [ 69 124]
Step [ 69 125]
Step [ 69 126]
Step [ 69 127]
Step [ 70 127]
Step [ 71 127]
Step [ 71 126]
Step [ 71 125]
Step [ 71 124]
Step [ 71 123]
Step [ 71 122]
Step [ 71 121]
Step [ 71 120]
Step [ 71 119]
Step [ 71 118]
Step [ 71 117]
Step [ 70 117]
Step [ 69 117]
Step [ 69 116]
Step [ 69 115]
Step [ 70 115]
Step [ 71 115]
Step [ 72 115]
Step [ 73 115]
Step [ 73 116]
Step [ 73 117]
Step [ 73 118]
Step [ 73 119]
Step [ 73 120]
Step [ 73 121]
Step [ 73 122]
Step [ 73 

In [10]:
shortcutsavings=np.array(shortcutsavings)
#print(np.unique(shortcutsavings,return_counts=True))

print(len(shortcutsavings[(shortcutsavings>=100).nonzero()]))
                    
                       

979012


In [11]:
print(len(track))

9417
