In [8]:
import numpy as np

In [105]:
seeds=[]
with open('input_22.txt') as f:
    for line in f:
        seeds.append(line.strip())
seeds=np.array(seeds).astype(int)
print(seeds)

[ 4832674 14802956  7210529 ... 14169598  3013442  4961581]


In [106]:
def mix(a,b):
    return a ^ b

def prune(a):
    return a % 16777216

def evolve(a):
    a = prune(mix(a,a*64))
    a = prune(mix(a,a // 32))
    a = prune(mix(a,a*2048))
    return a

In [109]:
secrets=seeds.copy()
lastdigs=np.array([seeds % 10])
for i in range(2000):
    secrets=evolve(secrets)
    lastdigs=np.concatenate((lastdigs,np.array([secrets%10])))
for seed,secret in zip(seeds,secrets):
    print (seed, secret)
print(sum(secrets))

4832674 8186085
14802956 16060909
7210529 3581487
7709095 14331752
6063251 11096256
12294789 8119288
15666951 4175670
12074106 9128738
15427686 13899897
1214891 12087848
15165649 11514818
3609602 4150418
10200989 2679493
16451437 84072
10915511 3938870
3479515 15186439
173864 4224277
1238342 6637814
3381843 15335578
14767788 14808063
16088065 2236221
15637051 9777274
15981887 14777742
15854806 3528684
4988920 15225220
7980791 4484251
11263142 12505941
8044640 12324709
4572291 12840916
328777 13939301
11851557 7392065
13706949 13395486
16451719 14846825
15991644 15647415
14668984 15491670
8852039 12602693
1685443 16470307
13814197 10819101
14117797 8658998
6281998 11616760
12395020 4294043
1681090 11210309
16476099 1113711
2171296 16530315
10155667 8014000
15490827 13932057
6723206 9987703
7272972 10745797
1788575 14414226
2950054 10876125
10917267 4900422
6862495 10073232
8153949 1697345
16559239 13806560
8572595 3395269
1821668 1912260
3417901 15840966
11375457 998641
3878450 6645533


In [110]:
print(lastdigs.shape)
diffs=np.empty_like(lastdigs)
for step in range(1,lastdigs.shape[0]):
    diffs[step,:]=lastdigs[step,:]-lastdigs[step-1,:]

(2001, 1586)


In [111]:
stencils=[]
for i in range(-9,10):
    for j in range(-9,10):
        if i+j >= 10 or i+j<=-10:
            continue
        for k in range (-9,10):
            if j+k>=10 or j+k <= -10 or i+j+k >=10 or i+j+k <= -10:
                continue
            for m in range (-9,10):
                if k+m >=10 or k+m <= -10 or j+k+m >=10 or j+k+m <=-10 or i+j+k+m >=10 or i+j+k+m <=-10:
                    continue
                stencils.append([i,j,k,m])
stencils=np.array(stencils)

In [112]:
print(stencils)
print(stencils.shape)

[[-9  0  0  0]
 [-9  0  0  1]
 [-9  0  0  2]
 ...
 [ 9  0  0 -2]
 [ 9  0  0 -1]
 [ 9  0  0  0]]
(40951, 4)


In [ ]:
bought=np.zeros(stencils.shape[0],dtype=int)
for count,stencil in enumerate(stencils):
    print(stencil)
    for monkey in range(len(seeds)):
        for step in range(4,2001):
            if all(diffs[step-3:step+1,monkey]==stencil[:]):
                bought[count]+=lastdigs[step,monkey]
                print('Bought', lastdigs[step,monkey], 'from', monkey)
                break

[-9  0  0  0]
[-9  0  0  1]
[-9  0  0  2]
[-9  0  0  3]
[-9  0  0  4]
[-9  0  0  5]
[-9  0  0  6]
[-9  0  0  7]
[-9  0  0  8]
[-9  0  0  9]
[-9  0  1 -1]
[-9  0  1  0]
Bought 1 from 0
[-9  0  1  1]
[-9  0  1  2]
[-9  0  1  3]
[-9  0  1  4]
[-9  0  1  5]
Bought 6 from 2
[-9  0  1  6]
[-9  0  1  7]
[-9  0  1  8]
[-9  0  2 -2]
[-9  0  2 -1]
[-9  0  2  0]
[-9  0  2  1]
[-9  0  2  2]
[-9  0  2  3]
[-9  0  2  4]
[-9  0  2  5]
[-9  0  2  6]
[-9  0  2  7]
[-9  0  3 -3]
[-9  0  3 -2]
Bought 1 from 0
[-9  0  3 -1]
[-9  0  3  0]
[-9  0  3  1]
[-9  0  3  2]
Bought 5 from 2
[-9  0  3  3]
[-9  0  3  4]
[-9  0  3  5]
Bought 8 from 3
[-9  0  3  6]
Bought 9 from 3
[-9  0  4 -4]
Bought 0 from 3
[-9  0  4 -3]
[-9  0  4 -2]
[-9  0  4 -1]
[-9  0  4  0]
[-9  0  4  1]
[-9  0  4  2]
[-9  0  4  3]
[-9  0  4  4]
[-9  0  4  5]
Bought 9 from 1
[-9  0  5 -5]
[-9  0  5 -4]
[-9  0  5 -3]
[-9  0  5 -2]
[-9  0  5 -1]
[-9  0  5  0]
Bought 5 from 3
[-9  0  5  1]
[-9  0  5  2]
[-9  0  5  3]
[-9  0  5  4]
[-9  0  6 -6]
[-

In [114]:
bought=np.zeros(stencils.shape[0],dtype=int)
for count,stencil in enumerate(stencils):
    print(stencil)
    for monkey in range(len(seeds)):
        diff=diffs[:,monkey]
        mask=(diff[1:-3]==stencil[0]) & (diff[2:-2]==stencil[1]) & (diff[3:-1]==stencil[2]) & (diff[4:]==stencil[3])
        found=np.nonzero(mask)[0]
        if len(found)>0:
            bought[count]+=lastdigs[found[0]+4,monkey]
            #print('Bought', lastdigs[found[0]+4,monkey], 'from', monkey)
#            print (lastdigs[found[0]-4:found[0]+5,monkey])

        #for step in range(4,2001):
        #print(np.nonzero(diffs[1:-3,monkey]==stencil[0]) & (diffs[2:-2,monkey]==stencil[1]) & (diffs[3:-1,monkey]==stencil[2]) & (diffs[4:,monkey]==stencil[3]))
        #print(found)
            #if all(diffs[step-3:step+1,monkey]==stencil[:]):
        #        bought[count]+=lastdigs[step,monkey]
        #        print('Bought', lastdigs[step,monkey], 'from', monkey)
        #        break

[-9  0  0  0]
[-9  0  0  1]
[-9  0  0  2]
[-9  0  0  3]
[-9  0  0  4]
[-9  0  0  5]
[-9  0  0  6]
[-9  0  0  7]
[-9  0  0  8]
[-9  0  0  9]
[-9  0  1 -1]
[-9  0  1  0]
[-9  0  1  1]
[-9  0  1  2]
[-9  0  1  3]
[-9  0  1  4]
[-9  0  1  5]
[-9  0  1  6]
[-9  0  1  7]
[-9  0  1  8]
[-9  0  2 -2]
[-9  0  2 -1]
[-9  0  2  0]
[-9  0  2  1]
[-9  0  2  2]
[-9  0  2  3]
[-9  0  2  4]
[-9  0  2  5]
[-9  0  2  6]
[-9  0  2  7]
[-9  0  3 -3]
[-9  0  3 -2]
[-9  0  3 -1]
[-9  0  3  0]
[-9  0  3  1]
[-9  0  3  2]
[-9  0  3  3]
[-9  0  3  4]
[-9  0  3  5]
[-9  0  3  6]
[-9  0  4 -4]
[-9  0  4 -3]
[-9  0  4 -2]
[-9  0  4 -1]
[-9  0  4  0]
[-9  0  4  1]
[-9  0  4  2]
[-9  0  4  3]
[-9  0  4  4]
[-9  0  4  5]
[-9  0  5 -5]
[-9  0  5 -4]
[-9  0  5 -3]
[-9  0  5 -2]
[-9  0  5 -1]
[-9  0  5  0]
[-9  0  5  1]
[-9  0  5  2]
[-9  0  5  3]
[-9  0  5  4]
[-9  0  6 -6]
[-9  0  6 -5]
[-9  0  6 -4]
[-9  0  6 -3]
[-9  0  6 -2]
[-9  0  6 -1]
[-9  0  6  0]
[-9  0  6  1]
[-9  0  6  2]
[-9  0  6  3]
[-9  0  7 -7]
[-9  0

In [115]:
print(max(bought))

1499


In [101]:
stencil=np.array([-2,1,-1,3])
#for monkey in range(len(seeds)):
monkey=1
diff=diffs[:,monkey]
mask=(diff[1:-3]==stencil[0]) & (diff[2:-2]==stencil[1]) & (diff[3:-1]==stencil[2]) & (diff[4:]==stencil[3])
print(mask)
print(mask.shape)
found=np.nonzero(mask)[0]
if len(found)>0:
    print (lastdigs[found[0]+4,monkey])

#for step in range(4,2001):
#            if lastdigs[step,monkey]==7:
#            print(lastdigs[step-4:step+1,monkey],diffs[step-3:step+1,monkey])#, stencil)
#            if all(diffs[step-3:step+1,monkey]==stencil[:]):
#                bought[count]+=lastdigs[step,monkey]
#                print('Bought', lastdigs[step,monkey], 'from', monkey)
#                break

[False False False ... False False False]
(1997,)
7


In [63]:
step=100
print(lastdigs[-5:,1], diffs[-4:,1])
print(lastdigs[:10,1], diffs[:10,1])

[0 7 4 0 8] [ 7 -3 -4  8]
[0 0 2 7 6 3 3 9 0 6] [ 0  0  2  5 -1 -3  0  6 -9  6]


In [64]:
reconst_ld=np.empty_like(lastdigs)
reconst_ld[0,:]=lastdigs[0,:]
for i in range(1,reconst_ld.shape[0]):
    reconst_ld[i,:]=reconst_ld[i-1,:]+diffs[i,:]
    

In [65]:
np.max(reconst_ld-lastdigs)

0

In [99]:
for i,diff in enumerate(diffs):
    print (i,diff)

0 [1 2 3 4]
1 [2 4 0 5]
2 [ 0 -4  0 -4]
3 [ 6  2 -2 -2]
4 [-4 -4  0  1]
5 [ 4  9  7 -1]
6 [-9 -9  0 -2]
7 [ 5  9 -4  5]
8 [ 4 -9  3 -3]
9 [-2  4  2  4]
10 [-5  2 -3 -7]
11 [-2 -5 -5  9]
12 [ 1 -1  6  0]
13 [ 2  5 -5 -7]
14 [6 1 5 4]
15 [-1  0 -5  3]
16 [-3  0  5 -9]
17 [2 2 0 9]
18 [-1 -7  0 -1]
19 [0 2 0 0]
20 [ 3 -3 -2 -7]
21 [-6  1  1  1]
22 [ 4 -1 -3  5]
23 [-2  4  4 -2]
24 [-3  4 -7  4]
25 [-1 -8  5 -9]
26 [ 2  5 -5  9]
27 [ 5 -2  1 -7]
28 [-3  0  5  6]
29 [-2 -2 -4 -5]
30 [2 7 3 0]
31 [-3 -5  4 -2]
32 [ 3  2 -9  1]
33 [3 4 7 5]
34 [ 0  0 -4  1]
35 [-1 -3  4  1]
36 [-3 -6 -7 -9]
37 [-4  3  7  1]
38 [7 3 0 6]
39 [-4 -1 -5 -5]
40 [ 2  3 -1  2]
41 [ 1  1  2 -3]
42 [-3 -4  3  7]
43 [ 4 -1  3 -5]
44 [-7 -3 -8 -1]
45 [ 1  8 -1  7]
46 [ 4 -1  5 -7]
47 [ 0 -1 -1 -1]
48 [ 3  1 -2  4]
49 [-2 -4  6 -1]
50 [ 2 -2 -6 -4]
51 [ 1  7 -2  0]
52 [-5 -5  0  5]
53 [ 3 -2  5  4]
54 [ 0  4 -4 -9]
55 [2 3 3 0]
56 [-8 -1  5  4]
57 [ 7 -5 -4 -4]
58 [ 0  2 -2  6]
59 [-8  3  3 -5]
60 [ 0 -7  1  0]
61 [7 0 1