In [12]:
import numpy as np
directions=np.array([[1,0],[0,1],[-1,0],[0,-1]])

In [13]:
area=[]
linecount = 0
with open('test_10a.txt') as f:
    for line in f:
        area.append(list(map(int,line.strip())))
maparr=np.array(area)
dimx=maparr.shape[0]
dimy=maparr.shape[1]
print(dimx,dimy,maparr)

4 4 [[0 1 2 3]
 [1 2 3 4]
 [8 7 6 5]
 [9 8 7 6]]


In [14]:
#Find trailheads
[thx,thy]=np.where(maparr==0)
ths=np.array([thx,thy]).transpose()
print(ths)

[[0 0]]


In [28]:
peaks=0
for th in ths:
    print('Trailhead',th)
    locs=np.array([th])
    for alt in range(1,10):
        print('Altitude', alt)
        climb=[]
        for loc in locs:
            #print('Location', loc)
            for dir in directions:
                #print ('direction', dir)
                if loc[0]+dir[0]>=0 and loc[1]+dir[1]>=0 and loc[0]+dir[0]<dimx and loc[1]+dir[1]<dimy:
                    if maparr[loc[0]+dir[0],loc[1]+dir[1]]==alt:
                        #print(alt,loc+dir)
                        climb.append(loc+dir)
        locs=np.array(np.unique(climb,axis=0))
        print('Altitude',alt,'Locations',locs)
    peaks += locs.shape[0]
print('Peaks',peaks)

Trailhead [0 0]
Altitude 1
Altitude 1 Locations [[0 1]
 [1 0]]
Altitude 2
Altitude 2 Locations [[0 2]
 [1 1]]
Altitude 3
Altitude 3 Locations [[0 3]
 [1 2]]
Altitude 4
Altitude 4 Locations [[1 3]]
Altitude 5
Altitude 5 Locations [[2 3]]
Altitude 6
Altitude 6 Locations [[2 2]
 [3 3]]
Altitude 7
Altitude 7 Locations [[2 1]
 [3 2]]
Altitude 8
Altitude 8 Locations [[2 0]
 [3 1]]
Altitude 9
Altitude 9 Locations [[3 0]]
Peaks 1
