In [36]:
import numpy as np
directions=np.array([[1,0],[0,1],[-1,0],[0,-1]])

In [40]:
area=[]
linecount = 0
with open('input_10.txt') as f:
    for line in f:
        area.append(list(map(int,line.strip())))
maparr=np.array(area)
dimx=maparr.shape[0]
dimy=maparr.shape[1]
print(dimx,dimy,maparr)

57 57 [[3 2 1 ... 3 0 0]
 [4 3 8 ... 2 1 1]
 [5 6 7 ... 2 3 2]
 ...
 [2 1 0 ... 7 6 6]
 [3 2 5 ... 1 2 5]
 [4 3 4 ... 1 3 4]]


In [41]:
#Find trailheads
[thx,thy]=np.where(maparr==0)
ths=np.array([thx,thy]).transpose()
print(ths)

[[ 0  3]
 [ 0  6]
 [ 0 22]
 [ 0 30]
 [ 0 31]
 [ 0 36]
 [ 0 38]
 [ 0 43]
 [ 0 48]
 [ 0 55]
 [ 0 56]
 [ 1  9]
 [ 1 11]
 [ 1 25]
 [ 1 48]
 [ 1 53]
 [ 2  3]
 [ 2 10]
 [ 2 20]
 [ 2 36]
 [ 2 47]
 [ 3 20]
 [ 3 22]
 [ 3 46]
 [ 4  1]
 [ 4  6]
 [ 4  8]
 [ 4 13]
 [ 4 20]
 [ 4 53]
 [ 5  8]
 [ 5 16]
 [ 5 32]
 [ 5 34]
 [ 6  0]
 [ 6 24]
 [ 6 30]
 [ 6 32]
 [ 6 44]
 [ 6 56]
 [ 7  5]
 [ 7  7]
 [ 7 14]
 [ 7 17]
 [ 7 36]
 [ 7 40]
 [ 7 55]
 [ 8 27]
 [ 8 33]
 [ 8 39]
 [ 8 49]
 [ 8 54]
 [ 8 56]
 [ 9  3]
 [ 9 17]
 [ 9 24]
 [ 9 34]
 [ 9 38]
 [10  2]
 [10 16]
 [11 12]
 [11 42]
 [11 48]
 [12  6]
 [12 13]
 [12 18]
 [12 24]
 [12 43]
 [13  0]
 [13 10]
 [13 21]
 [13 27]
 [13 34]
 [13 40]
 [13 48]
 [14  6]
 [14 10]
 [14 28]
 [14 50]
 [14 51]
 [15  4]
 [15 17]
 [15 22]
 [15 36]
 [15 49]
 [15 53]
 [15 56]
 [16  6]
 [16  8]
 [16 18]
 [16 33]
 [16 47]
 [17  7]
 [17 24]
 [17 31]
 [17 46]
 [17 48]
 [18  7]
 [18 18]
 [18 38]
 [18 41]
 [19  0]
 [19 19]
 [19 21]
 [19 33]
 [19 34]
 [19 46]
 [19 53]
 [20  4]
 [20 15]
 [20 28]
 

In [42]:
peaks=0
for th in ths:
    print('Trailhead',th)
    locs=np.array([th])
    for alt in range(1,10):
        print('Altitude', alt)
        climb=[]
        for loc in locs:
            #print('Location', loc)
            for dir in directions:
                #print ('direction', dir)
                if loc[0]+dir[0]>=0 and loc[1]+dir[1]>=0 and loc[0]+dir[0]<dimx and loc[1]+dir[1]<dimy:
                    if maparr[loc[0]+dir[0],loc[1]+dir[1]]==alt:
                        #print(alt,loc+dir)
                        climb.append(loc+dir)
        #locs=np.array(np.unique(climb,axis=0))
        locs=np.array(climb)
        print('Altitude',alt,'Locations',locs)
    peaks += locs.shape[0]
print('Peaks',peaks)

Trailhead [0 3]
Altitude 1
Altitude 1 Locations [[0 2]]
Altitude 2
Altitude 2 Locations [[0 1]]
Altitude 3
Altitude 3 Locations [[1 1]
 [0 0]]
Altitude 4
Altitude 4 Locations [[1 0]
 [1 0]]
Altitude 5
Altitude 5 Locations [[2 0]
 [2 0]]
Altitude 6
Altitude 6 Locations [[2 1]
 [2 1]]
Altitude 7
Altitude 7 Locations [[2 2]
 [2 2]]
Altitude 8
Altitude 8 Locations [[1 2]
 [1 2]]
Altitude 9
Altitude 9 Locations [[1 3]
 [1 3]]
Trailhead [0 6]
Altitude 1
Altitude 1 Locations [[0 5]]
Altitude 2
Altitude 2 Locations [[0 4]]
Altitude 3
Altitude 3 Locations [[1 4]]
Altitude 4
Altitude 4 Locations [[1 5]]
Altitude 5
Altitude 5 Locations [[2 5]]
Altitude 6
Altitude 6 Locations [[2 6]]
Altitude 7
Altitude 7 Locations [[1 6]]
Altitude 8
Altitude 8 Locations [[1 7]]
Altitude 9
Altitude 9 Locations [[0 7]]
Trailhead [ 0 22]
Altitude 1
Altitude 1 Locations [[ 0 21]]
Altitude 2
Altitude 2 Locations [[ 0 20]]
Altitude 3
Altitude 3 Locations [[ 1 20]
 [ 0 19]]
Altitude 4
Altitude 4 Locations [[ 1 19]
 [ 1 